apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapp-group
  labels:
    app: restapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapp
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
        - name: myrest
          image: tethmado/myapp
          ports:
            - containerPort: 80