apiVersion: v1
kind: Service
metadata:
  name: restapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: restapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31234