name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: '21'


      - name: Build gradle environment
        run: ./gradlew build

      - name: Build the Docker image from the Dockerfile
        run: docker build . -t myapp

      - name: Run the Docker container on port 8080
        run: docker run -d -p 8080:8080 myapp

      - name: Test the RESTful service
        run: |
          # Wait for the container to start up
          sleep 5
          
          # Send a GET request to the service
          response=$(curl http://localhost:8080/friendvendor/fib?length=3)
          
          # Check that the response is "[0, 1, 1]"
          if [ "$response" == '[0, 1, 1]' ]; then
            echo "Test passed!"
          else
            echo "Test failed. Expected '[0, 1, 1]', got '$response'"
            exit 1
          fi